@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Contact as ContactPackage <<Rectangle>>{
    Class Contact
    Class ContactName
    Class Phone
    Class Email
    Class Address
}

AddressBook *-left-> "1" UniqueContactList

UniqueContactList -down-> "*" Contact

Contact -up-> "*" Tag

Contact *--> ContactName
Contact *--> Phone
Contact *--> Email
Contact *--> Address
@enduml
